name: Deploy Website

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Replace these commands with your actual build and deployment steps
          npm install
          npm run build
          node index.js
          cp -R build/* /path/to/your/github/pages/repo

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update website"
          git push

